import { useMemo, useState } from 'react';
import { Plus, UserRound, X, CheckCircle2, Shield, LockKeyhole, Crown, Wallet, Percent } from 'lucide-react';
import { addStaff, deleteStaff, updateStaff, useStaff, useStaffEarnings } from '@/lib/hooks';
import type { Staff } from '@/lib/supabase';
import { formatCurrency, formatDateTime } from '@/lib/utils';

const SESSION_KEY='propos-current-staff-v2';
function currentStaffId(){ try { return (JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null') as any)?.id || ''; } catch { return ''; } }

export default function StaffPage(){
 const {staff,error:staffError,reload}=useStaff(); const mineId=currentStaffId(); const mine=staff.find(s=>s.id===mineId) || null; const {earnings}=useStaffEarnings(mine?.id,31);
 const totalMine=useMemo(()=>earnings.reduce((s,e)=>s+Number(e.earning_amount||0),0),[earnings]);
 const todayMine=useMemo(()=>{const d=new Date(); return earnings.filter(e=>{const x=new Date(e.created_at); return x.getFullYear()===d.getFullYear()&&x.getMonth()===d.getMonth()&&x.getDate()===d.getDate();}).reduce((s,e)=>s+Number(e.earning_amount||0),0)},[earnings]);
 const [open,setOpen]=useState(false); const [name,setName]=useState(''); const [pin,setPin]=useState(''); const [role,setRole]=useState<Staff['role']>('cashier'); const [rate,setRate]=useState('5');
 async function add(){if(!pin.trim()){window.alert('Personel PIN/şifre alanı zorunludur.');return;} const r=await addStaff(name,pin,role,Number(rate));if(r.data){setName('');setPin('');setRole('cashier');setRate('5');setOpen(false);reload();}else{window.alert(r.error || 'Personel eklenemedi.');}}
 async function promoteYunus(id:string){const ok=await updateStaff(id,{role:'admin'}); if(ok) reload(); else window.alert('Yunus yönetici yapılamadı.');}
 async function changeRole(id:string,newRole:Staff['role']){const ok=await updateStaff(id,{role:newRole}); if(ok) reload(); else window.alert('Yetki değiştirilemedi.');}
 async function changeRate(id:string,v:string){const n=Math.max(0,Math.min(100,Number(v)||0)); const ok=await updateStaff(id,{earning_rate:n}); if(ok) reload(); else window.alert('Çalışan payı güncellenemedi.');}
 return <div className="flex h-screen flex-col overflow-hidden">
  <div className="border-b border-slate-200 bg-white px-6 py-4 flex items-center justify-between"><div><h1 className="text-xl font-bold text-slate-800">Personel & Yetki</h1><p className="text-sm text-slate-500">Yetki, PIN ve çalışan tahsilat paylarını yönetin.</p></div><button className="btn-primary" onClick={()=>setOpen(true)}><Plus size={18}/> Personel Ekle</button></div>
  <div className="flex-1 overflow-y-auto p-6">
   {mine && <div className="mx-auto mb-6 max-w-5xl grid gap-4 sm:grid-cols-3"><div className="card p-5"><p className="text-xs text-slate-500">Bugünkü kazancım</p><p className="mt-1 text-3xl font-black text-emerald-700">{formatCurrency(todayMine)}</p><p className="mt-1 text-xs text-slate-400">Tahsil edilen borçlardan</p></div><div className="card p-5"><p className="text-xs text-slate-500">Son 31 gün</p><p className="mt-1 text-3xl font-black text-slate-800">{formatCurrency(totalMine)}</p><p className="mt-1 text-xs text-slate-400">Pay oranım: %{Number(mine.earning_rate||0).toFixed(2)}</p></div><div className="card p-5"><div className="flex items-center gap-2 text-slate-700"><Wallet size={18}/> <span className="font-semibold">Kazanç hareketleri</span></div><p className="mt-2 text-sm text-slate-500">Müşteri borç ödemesi yapıldığında çalışan payı otomatik oluşur.</p></div></div>}
   <div className="mx-auto mb-6 max-w-5xl grid gap-4 md:grid-cols-3"><div className="card p-4"><div className="flex items-center gap-2 font-semibold text-slate-800"><LockKeyhole size={18}/> Admin</div><p className="mt-2 text-xs text-slate-500">Tüm modüller ve personel/ayarlar dahil tam yetki.</p></div><div className="card p-4"><div className="flex items-center gap-2 font-semibold text-slate-800"><Shield size={18}/> Müdür</div><p className="mt-2 text-xs text-slate-500">Satış, ürün, stok, barkod, müşteri, kasa ve raporlar.</p></div><div className="card p-4"><div className="flex items-center gap-2 font-semibold text-slate-800"><UserRound size={18}/> Kasiyer</div><p className="mt-2 text-xs text-slate-500">Satış ve müşteri/cari ekranı.</p></div></div>
   <div className="mx-auto max-w-5xl grid gap-4 md:grid-cols-2">{staff.map(s=><div key={s.id} className="card p-5"><div className="mb-4 flex items-center gap-3"><div className="h-11 w-11 rounded-full bg-slate-100 flex items-center justify-center"><UserRound size={22}/></div><div className="min-w-0"><p className="font-bold text-slate-800">{s.name}</p><p className="text-xs text-slate-500">{s.role==='admin'?'Yönetici / Admin':s.role==='manager'?'Müdür':'Kasiyer'}</p></div></div><div className="space-y-3"><div className="flex items-center justify-between text-sm"><span className={s.active?'text-emerald-600':'text-slate-400'}>{s.active?'Aktif':'Pasif'}</span><button onClick={()=>updateStaff(s.id,{active:!s.active}).then(reload)} className="text-xs text-teal-700">{s.active?'Pasifleştir':'Aktifleştir'}</button></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-[1fr_auto_auto]"><select value={s.role} onChange={e=>changeRole(s.id,e.target.value as Staff['role'])} className="input py-1.5 text-xs"><option value="cashier">Kasiyer</option><option value="manager">Müdür</option><option value="admin">Admin</option></select><div className="flex items-center gap-1"><Percent size={14} className="text-slate-400"/><input type="number" min="0" max="100" step="0.01" className="input w-24 py-1.5 text-xs" value={s.earning_rate ?? 0} onChange={e=>changeRate(s.id,e.target.value)} title="Çalışan payı (%)"/></div>{s.name.trim().toLocaleLowerCase('tr-TR').includes('yunus') && s.role!=='admin' ? <button onClick={()=>promoteYunus(s.id)} className="inline-flex items-center justify-center gap-1 rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-white hover:bg-amber-600"><Crown size={14}/> En yüksek yap</button> : <button onClick={async()=>{if(!confirm(`${s.name} tamamen silinsin mi?`)) return; const ok=await deleteStaff(s.id); if(ok) reload(); else alert('Personel silinemedi.');}} className="inline-flex items-center justify-center rounded-lg border border-red-200 p-2 text-red-500 hover:bg-red-50" title="Personeli sil"><X size={15}/></button>}</div></div></div>)}{staff.length===0&&<div className="card p-8 text-center text-slate-400 md:col-span-2">Henüz personel yok.</div>}</div>
   {staffError&&<div className="mx-auto mt-4 max-w-5xl rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">{staffError}</div>}
   {mine && <div className="mx-auto mt-6 max-w-5xl card overflow-hidden"><div className="border-b border-slate-200 px-5 py-4 font-semibold">Son kazanç hareketlerim</div>{earnings.length===0?<div className="p-6 text-sm text-slate-400">Henüz müşteri tahsilatından oluşan kazanç yok.</div>:<div className="divide-y divide-slate-100">{earnings.slice(0,20).map(e=><div key={e.id} className="flex items-center justify-between px-5 py-3"><div><p className="text-sm font-semibold text-slate-700">Tahsilat: {formatCurrency(e.amount_paid)}</p><p className="text-xs text-slate-400">%{Number(e.rate_percent).toFixed(2)} çalışan payı • {formatDateTime(e.created_at)}</p></div><p className="font-bold text-emerald-700">+{formatCurrency(e.earning_amount)}</p></div>)}</div>}</div>}
  </div>
  {open&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4" onClick={()=>setOpen(false)}><div className="card w-full max-w-md p-6" onClick={e=>e.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Yeni Personel</h2><button onClick={()=>setOpen(false)}><X size={20}/></button></div><div className="space-y-3"><input className="input" placeholder="Ad Soyad" value={name} onChange={e=>setName(e.target.value)}/><input className="input font-mono" placeholder="PIN / Şifre *" value={pin} onChange={e=>setPin(e.target.value)} maxLength={8}/><select className="input" value={role} onChange={e=>setRole(e.target.value as Staff['role'])}><option value="cashier">Kasiyer</option><option value="manager">Müdür</option><option value="admin">Admin</option></select><div><label className="label">Çalışan payı (%)</label><input type="number" min="0" max="100" step="0.01" className="input" value={rate} onChange={e=>setRate(e.target.value)}/><p className="mt-1 text-xs text-slate-400">Müşteri borç ödemesi yaptığında bu oran ödeme tutarı üzerinden hesaplanır.</p></div><button onClick={add} className="btn-primary w-full py-3"><CheckCircle2 size={18}/> Personeli Kaydet</button></div></div></div>}
 </div>
}
